-- =========================================================
-- CULONES-RPG BOT · SQL ACTUAL
-- =========================================================
-- El sistema de códigos y las tablas admin_codes/bot_config quedaron
-- retirados. Ejecuta las migraciones de la web en orden y, al final:
--
--   migration_021_discord_auth_and_forum.sql
--
-- Esa migración crea:
--   discord_guild_config
--   guide_forum_publications
--   guide_forum_jobs
--   guide_forum_tag_map
--   log_discord_publications.message_map
--   auditoría vinculada a Discord OAuth
--
-- La copia de esa migración está en este mismo directorio.
-- =========================================================
